config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'home/index'  
  resources :high_scores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable,  and :omniauthable
  devise :confirmable,
         :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable,
         :trackable, 
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_high_score, only: %i[ show edit update destroy ]

  # GET /high_scores or /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1 or /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores or /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to high_score_url(@high_score), notice: "High score was successfully created." }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1 or /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to high_score_url(@high_score), notice: "High score was successfully updated." }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1 or /high_scores/1.json
  def destroy
    @high_score.destroy

    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: "High score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/high_scores/_form.html.erb
<%= form_with(model: high_score) do |form| %>
  <% if high_score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
        <% high_score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :game, style: "display: block" %>
    <%= form.text_field :game %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/high_scores/_high_score.html.erb
<div id="<%= dom_id high_score %>">
  <p>
    <strong>Game:</strong>
    <%= high_score.game %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= high_score.score %>
  </p>

</div>

app/views/high_scores/edit.html.erb
<h1>Editing high score</h1>

<%= render "form", high_score: @high_score %>

<br>

<div>
  <%= link_to "Show this high score", @high_score %> |
  <%= link_to "Back to high scores", high_scores_path %>
</div>

app/views/high_scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>High scores</h1>

<div id="high_scores">
  <% @high_scores.each do |high_score| %>
    <%= render high_score %>
    <p>
      <%= link_to "Show this high score", high_score %>
    </p>
  <% end %>
</div>

<%= link_to "New high score", new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high score</h1>

<%= render "form", high_score: @high_score %>

<br>

<div>
  <%= link_to "Back to high scores", high_scores_path %>
</div>

app/views/high_scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @high_score %>

<div>
  <%= link_to "Edit this high score", edit_high_score_path(@high_score) %> |
  <%= link_to "Back to high scores", high_scores_path %>

  <%= button_to "Destroy this high score", @high_score, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>